theme: jekyll-theme-cayman
# Site settings
title: 离人漾    				  	#你博客的标题
SEOTitle: 你的博客 | You Blog    	 #显示在浏览器上搜索的时候显示的标题
header-img: img/post-bg-rwd.jpg  	#显示在首页的背景图片
email: chiz1735@gmail.com	
description: "一人成军，独立开发者"  			 #网站介绍
keyword: "blog, 独立开发者, 数字游民, python, 数据分析, 爬虫, 运营， 产品" #关键词
url: "https://suesam.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写

# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "一人军队"
#sidebar-avatar:/img/avatar-by.JPG      # 你的个人头像 这里你可以改成我在img文件夹中的两张备用照片 img/avatar-m 或 avatar-g

# SNS settings
RSS: false
#weibo_username:     username
#zhihu_username:     username
#github_username:    username
#facebook_username:  username
#:	jianshu_id
